"""Tests for the plan review subagent feature.

Verifies that the plan review checklist template exists, the lead
instructions contain the review cycle, and the plan format guide
includes agent authoring hints.
"""

import re

import pytest

from conftest import CLAUDE_MD, PLAN_FORMAT_TEMPLATE, PLAN_REVIEW_CHECKLIST_TEMPLATE

pytestmark = pytest.mark.static


# --- Checklist template structure ---


def test_plan_review_checklist_exists():
    assert PLAN_REVIEW_CHECKLIST_TEMPLATE.exists(), (
        "Missing plan-review-checklist.md in ensure-ai-dirs skill — "
        "the plan review subagent needs this checklist as its review "
        "criteria"
    )


def test_checklist_has_auto_generated_header():
    """The checklist must have the auto-generated warning like other synced files."""
    content = PLAN_REVIEW_CHECKLIST_TEMPLATE.read_text()
    assert "Auto-generated by /ensure-ai-dirs" in content, (
        "plan-review-checklist.md must include the auto-generated "
        "header — without it, users may edit the synced copy instead "
        "of the source template"
    )


REQUIRED_CHECKLIST_SECTIONS = [
    "Self-Containment",
    "Escape Hatches",
    "Weasel and Ambiguous Language",
    "Stale Artifacts",
    "Future-Agent Escape Infrastructure",
    "Cross-Reference Staleness",
    "Task Description Completeness",
    "Goal Covers User Request",
    "Goal-Task Alignment",
    "Format Compliance",
    "Separable Concerns",
]


@pytest.mark.parametrize("section", REQUIRED_CHECKLIST_SECTIONS)
def test_checklist_contains_required_section(section):
    content = PLAN_REVIEW_CHECKLIST_TEMPLATE.read_text()
    assert section in content, (
        f"plan-review-checklist.md must contain a '{section}' section — "
        f"this review category catches a documented class of plan defects"
    )


def test_checklist_includes_clean_report_instruction():
    """The checklist must tell the subagent what to return when no issues are found."""
    content = PLAN_REVIEW_CHECKLIST_TEMPLATE.read_text()
    assert "No issues found" in content, (
        "plan-review-checklist.md must include 'No issues found' as the "
        "clean-report phrase — the lead uses this to detect when the "
        "review cycle can stop"
    )


# --- Plan format authoring hints ---


def test_plan_format_contains_agent_comments():
    """plan-format.md must contain <!-- agent: --> authoring hints."""
    content = PLAN_FORMAT_TEMPLATE.read_text()
    agent_comments = re.findall(r"<!--\s*agent:", content)
    assert len(agent_comments) >= 3, (
        f"plan-format.md has {len(agent_comments)} agent comments — "
        f"expected at least 3 (Goal, Context, Tasks sections). "
        f"These comments guide the lead when writing plans"
    )


def test_lead_instructions_pass_user_request_to_reviewer(lead_instructions):
    """Lead must pass the user's original request to the plan-reviewer."""
    text = lead_instructions.lower()
    assert "user" in text and "original request" in text, (
        "CLAUDE.md must instruct the lead to pass the user's "
        "original request to the plan-reviewer — without it, "
        "the reviewer has no ground truth to verify the goal "
        "captures the full scope of what was asked"
    )


def test_plan_format_goal_hint():
    """Goal section must have a self-containment hint."""
    content = PLAN_FORMAT_TEMPLATE.read_text()
    goal_idx = content.index("### Goal")
    # Find the next section after Goal
    context_idx = content.index("### Context")
    goal_section = content[goal_idx:context_idx]
    assert "<!-- agent:" in goal_section and "self-contained" in goal_section, (
        "plan-format.md Goal section must have an agent comment about "
        "self-containment — plans that reference other plan files are "
        "the most common plan defect"
    )


def test_plan_format_tasks_escape_hatch_hint():
    """Tasks section must have an escape-hatch warning."""
    content = PLAN_FORMAT_TEMPLATE.read_text()
    tasks_idx = content.index("### Tasks")
    tasks_section = content[tasks_idx:]
    assert "<!-- agent:" in tasks_section and "escape hatch" in tasks_section.lower(), (
        "plan-format.md Tasks section must have an agent comment warning "
        "against escape hatches in acceptance criteria"
    )


# --- Lead instructions reference plan review ---


@pytest.fixture
def lead_instructions():
    return CLAUDE_MD.read_text()


def test_lead_instructions_reference_plan_review_subagent(lead_instructions):
    """Lead instructions must describe the plan review subagent."""
    text = lead_instructions.lower()
    assert "review the plan via subagent" in text or (
        "plan review" in text and "subagent" in text
    ), (
        "CLAUDE.md must instruct the lead to launch a subagent for "
        "plan review — without independent review, the lead's own "
        "planning bias goes unchecked"
    )


def test_lead_instructions_reference_review_cycle(lead_instructions):
    """The plan review must be a cycle, not a one-shot check."""
    text = lead_instructions.lower()
    assert "repeat until" in text or "re-launch" in text, (
        "CLAUDE.md must describe the plan review as a cycle — "
        "re-launch the subagent after revisions until it reports "
        "no issues. A one-shot review misses issues introduced "
        "during revision"
    )


def test_lead_instructions_reference_checklist(lead_instructions):
    """Lead instructions must reference the plan review checklist."""
    assert "plan-review-checklist.md" in lead_instructions, (
        "CLAUDE.md must reference plan-review-checklist.md — "
        "the subagent needs to know which file to use as its "
        "review criteria"
    )


def test_lead_instructions_review_before_user_presentation(lead_instructions):
    """Plan review must happen before presenting to the user."""
    text = lead_instructions
    review_match = re.search(
        r"(\d+)\.\s+\*\*Review the plan", text
    )
    present_match = re.search(
        r"(\d+)\.\s+\*\*Present the plan to the user", text
    )
    assert review_match and present_match, (
        "CLAUDE.md must have both a 'Review the plan' step and a "
        "'Present the plan to the user' step in the Planning section"
    )
    review_step = int(review_match.group(1))
    present_step = int(present_match.group(1))
    assert review_step < present_step, (
        f"Plan review (step {review_step}) must come before user "
        f"presentation (step {present_step}) — the user should see "
        f"a plan that has already passed automated review"
    )


def test_lead_instructions_commit_after_approval(lead_instructions):
    """Plan commit must come after user approval, not before."""
    text = lead_instructions
    present_match = re.search(
        r"(\d+)\.\s+\*\*Present the plan to the user", text
    )
    commit_match = re.search(
        r"(\d+)\.\s+\*\*Commit the plan", text
    )
    assert present_match and commit_match, (
        "CLAUDE.md must have both a 'Present' and 'Commit' step"
    )
    present_step = int(present_match.group(1))
    commit_step = int(commit_match.group(1))
    assert present_step < commit_step, (
        f"User presentation (step {present_step}) must come before "
        f"plan commit (step {commit_step}) — plans are committed "
        f"only after user approval"
    )


def test_lead_instructions_user_rejection_restarts_review(lead_instructions):
    """User rejection must restart the review cycle."""
    text = lead_instructions.lower()
    assert "restart the review cycle" in text or "step 6" in text, (
        "CLAUDE.md must instruct the lead to restart the review cycle "
        "when the user requests changes — revisions based on user "
        "feedback can reintroduce issues"
    )


def test_lead_instructions_reference_plan_reviewer_agent(lead_instructions):
    """Lead instructions must reference the plan-reviewer agent by name."""
    assert "plan-reviewer" in lead_instructions, (
        "CLAUDE.md must reference the plan-reviewer agent by name — "
        "the agent file defines the review process and output format"
    )


# --- Scope bleed prevention ---


def test_lead_instructions_prohibit_other_tasks_in_dispatch(lead_instructions):
    """Lead must not include other tasks' descriptions in developer dispatch."""
    text = lead_instructions.lower()
    assert "do not include other tasks" in text, (
        "CLAUDE.md must prohibit including other tasks' descriptions "
        "in the developer dispatch message — the developer attends to "
        "all visible context and pulls scope from future tasks into "
        "the current one, corrupting plan progress tracking"
    )


def test_lead_instructions_prohibit_plan_file_path_to_developer(lead_instructions):
    """Lead must not send the plan file path to the developer."""
    text = lead_instructions.lower()
    assert "do not send the plan file path" in text, (
        "CLAUDE.md must prohibit sending the plan file path to the "
        "developer — if the developer reads the full plan, it sees "
        "all tasks and scope bleed occurs regardless of what the "
        "dispatch message contains"
    )
